config/routes.rb
Rails.application.routes.draw do

  if Rails.env.production?
    devise_for :users, :controllers => { :registrations => "users#registrations" } 
  else
    devise_for :users
  end

  root to: 'homes#show'


  get '/why', to: 'thoughts#show'
  get '/why/edit', to: 'thoughts#edit'
  patch '/why/update', to: 'thoughts#update'

  get '/what', to: 'activities#show'
  get '/what/edit', to: 'activities#edit'
  patch '/what/update', to: 'activities#update'


  get '/how', to: 'pages#how'
  get '/contact', to: 'pages#contact'


  get '/about', to: 'featured_users#index'
  post '/about', to: 'featured_users#create'
  get '/about/edit', to: 'featured_users#edit'
  patch '/about/update', to: 'featured_users#update'
  delete '/about/destroy', to: 'featured_users#destroy'

  get '/home/edit', to: 'homes#edit'
  patch '/home/update', to: 'homes#update'

  get '/blog', to: 'blogs#show'
  get '/blog/edit', to: 'blogs#edit'
  patch '/blog/update', to: 'blogs#update'

  get '/gifmemore', to: 'giphies#show'
  post '/gifmemore', to: 'giphies#create'
  get '/gifmemore/edit', to: 'giphies#edit'
  patch '/gifmemore/update', to: 'giphies#update'
  delete '/gifmemore/destroy', to: 'giphies#destroy'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  mount_uploader :photo, PhotoUploader
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/featured_user.rb
class FeaturedUser < ApplicationRecord
  mount_uploader :photo, PhotoUploader
end

app/models/giphy.rb
class Giphy < ApplicationRecord
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/thought.rb
class Thought < ApplicationRecord
  mount_uploader :photo, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]
  before_action :set_activity
  def show
    @activity_path = what_edit_path
  end

  def edit
  end

  def update
    if @activity.update(activities_params)
      redirect_to what_path
    else
      render 'edit'
    end
  end

  private

  def activities_params
    params.require(:activity).permit(:header, :description, :photo, :photo_cache)
  end

  def set_activity
    @activity = Activity.first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]
  before_action :set_blog
  def show
    @post_collection = Blogposts::BlogpostService.new(@blog.user).call
    @blog_path = blog_edit_path(@blog)
  end

  def edit
  end

  def update
    if @blog.update(blogs_params)
      redirect_to blog_path
    else
      render 'edit'
    end
  end

  private

  def blogs_params
    params.require(:blog).permit(:user)
  end

  def set_blog
    @blog = Blog.first
  end
end

app/controllers/featured_users_controller.rb
class FeaturedUsersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:edit, :update, :create, :destroy]
  before_action :set_featured_user, only: [:update, :destroy]

  def index
    @featured_users = FeaturedUser.all
    @featured_user_path = about_edit_path
  end

  def create
    @featured_user = FeaturedUser.new(featured_user_params)
    if @featured_user.save
      redirect_to about_path
    else
      render 'edit'
    end
  end

  def edit
    @featured_users = FeaturedUser.all
    @featured_user = FeaturedUser.new
  end

  def update
    if @featured_user.update(featured_user_params)
      redirect_to about_path
    else
      render 'edit'
    end
  end

  def destroy
    @featured_user.destroy
    redirect_to about_edit_path
  end

  private

  def set_featured_user
    @featured_user = FeaturedUser.find(params[:featured_user][:id])
  end

  def featured_user_params
    params.require(:featured_user).permit(:name, :description, :photo, :photo_cache)
  end
end

app/controllers/giphies_controller.rb
class GiphiesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:edit, :update, :destroy]

  def show
    @giphy_path = gifmemore_edit_path
    @giphy = Giphy.new
    set_default
    @giphies = Giphy.all
  end

  def create
    @giphy = Giphy.new(giphy_params)
    if @giphy.save
      redirect_to gifmemore_path
    else
      render 'show'
    end
  end

  def edit
    @giphies = Giphy.all
  end

  def update
    @giphy = Giphy.find(params[:giphy][:id].to_i)
    remove_old_default
    @giphy.default = true
    if @giphy.save
      redirect_to gifmemore_edit_path
    end
  end

  def destroy
    @giphy = Giphy.find(params[:giphy][:id].to_i)
    @giphy.destroy
    redirect_to gifmemore_edit_path
  end

  private

  def set_default
    @giphy_default = Giphy.find_by_default(true) || "http://media4.giphy.com/media/3o6gaW2l0FJB0jt7MY/giphy.gif"
  end

  def remove_old_default
    old_default = Giphy.find_by_default(true)
    unless old_default.nil?
      old_default.default = false
      old_default.save
    end
  end

  def giphy_params
    params.require(:giphy).permit(:url, :creator, :default, :message)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]
  before_action :set_home
  def show
    @home_path = home_edit_path
  end

  def edit
  end

  def update
    if @home.update(homes_params)
      redirect_to home_path
    else
      render 'edit'
    end
  end

  private

  def homes_params
    params.require(:home).permit(:header, :content)
  end

  def set_home
    @home = Home.first
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
    @home_text = {
      header: "we unlock creativity",
      content: "allowing people to reach their full potential. 
      We are on a mission to change the world of work - 
      using creative principles, building solid team cultures and collecting gifs along the way"
    }
  end

  def blog
    @posts = Blogposts::BlogpostService.new('unless-io').call
  end

  def contact
    @api_key = ENV["GOOGLE_MAPS_API_KEY"]
  end
end

app/controllers/thoughts_controller.rb
class ThoughtsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]
  before_action :set_thought
  def show
    @thought_path = why_edit_path
  end

  def edit
  end

  def update
    if @thought.update(thoughts_params)
      redirect_to why_path
    else
      render 'edit'
    end
  end

  private

  def thoughts_params
    params.require(:thought).permit(:header, :description, :photo, :photo_cache)
  end

  def set_thought
    @thought = Thought.first
  end
end

app/controllers/users/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def new
    flash[:info] = 'Registrations are not open yet, but please check back soon'
    redirect_to root_path
  end

  def create
    flash[:info] = 'Registrations are not open yet, but please check back soon'
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/activities/edit.html.erb
<div class="devise-form-wrapper">
  <div class="devise-form">
  <%= simple_form_for @activity, url: what_update_path do |f| %>
    <%= f.input :header %>
    <%= f.input :description %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.submit class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/activities/show.html.erb
<%= render partial: "shared/edit_button", locals: { partial_path: @activity_path } %>

<div class="content-box-cover" style="background-image: url(<%= @activity.photo %>);">
  <div class="content-box-content-container">
    <h2>
      <%= @activity.header %>
    </h2>
    <p>
      <%= @activity.description %>
    </p>
  </div>
</div>

app/views/blogs/edit.html.erb
<div class="devise-form-wrapper">
  <div class="devise-form">
    <%= simple_form_for @blog, url: blog_update_path do |f| %>
    <%= f.input :user %>
    <p>
      <em>
        Note:
      </em>
      Use a '@' for users and just the regular name for organizations.
    </p>
    <%= f.submit class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/blogs/show.html.erb
<%= render partial: "shared/edit_button", locals: { partial_path: @blog_path } %>

<div class="blogposts">
  <h2>
    Blog
  </h2>
  <div class="container">
    <div class="row">
      <% if @post_collection.is_a?(Array) %>
      <% @post_collection.each do |post| %>
      <div class="col-xs-12 col-lg-6 col-lg-offset-3">
        <%= raw(post["description"]) %>
      </div>
      <% end %>
      <% else %>
      <div class="col-xs-12 col-lg-6 col-lg-offset-3">
        <%= raw(@post_collection["description"]) %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/featured_users/edit.html.erb
<h2 class="text-center marged-top">
  Edit featured users
  <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
    Add a new user
  </button>
</h2>
<p class="text-center">
  <span>
    Note:
  </span>
  you can highlight text by placing span tags around them e.g.  &lt;span&gt;hello&lt;/span&gt;
</p>



<div class="collapse" id="collapseExample">
  <div class="well">
    <%= simple_form_for @featured_user, url: about_path do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.submit class: "btn btn-primary" %>
    <% end %>
  </div>
</div>




<div class="container">
  <div class="row">
    <% @featured_users.each do |featured_user| %>
    <div class="col-xs-12 col-lg-6">
      <div class="featured-user-container">
        <%= cl_image_tag featured_user.photo, height: 200, width: 200, crop: :fill, class: 'img-rounded' %>
        <h3>
          <%= featured_user.name %>
        </h3>
        <p>
          <%= raw(featured_user.description) %>
        </p>
        <%= simple_form_for featured_user, url: about_update_path do |f| %>
        <%= f.input :name %>
        <%= f.input :id, as: :hidden %>
        <%= f.input :description %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.submit class: "btn btn-primary" %>
        <% end %>
        <div class="remove-featured-user">
        <%= simple_form_for featured_user, url: about_destroy_path, method: :delete do |f| %>
          <%= f.input :id, as: :hidden %>
          <%= f.submit value: "remove", class: 'btn btn-danger', data: {confirm: "Are you sure you want to remove #{featured_user.name}?"} %>
          <% end %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/featured_users/index.html.erb
<%= render partial: "shared/edit_button", locals: { partial_path: @featured_user_path } %>

<h2 class="text-center marged-small">
  who we are
</h2>

<div class="container">
  <div class="row">
    <% @featured_users.each do |featured_user| %>
    <div class="col-xs-12 col-lg-4">
      <div class="featured-user-container">
        <%= cl_image_tag featured_user.photo, height: 200, width: 200, crop: :fill, class: 'img-rounded' %>
        <h3>
          <%= featured_user.name %>
        </h3>
        <p>
          <%= raw(featured_user.description) %>
        </p>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/giphies/edit.html.erb
<div class="container">
  <div class="row">
    <h2 class="text-center marged">
      View and edit <%= link_to "all giphies", gifmemore_path %>
    </h2>
    <div class="row">
      <% @giphies.each do |giphy| %>
      <div class="col-xs-6 col-lg-3">
        <div class="giphy-image-container giphy-image-container-small" style="background-image:url('<%= giphy.url %>');"></div>
        <div class="giphy-image-description">
          <ul class="list-unstyled">
            <li>
              <div class="actions">
                <% unless giphy.default %>
                <%= simple_form_for giphy, url: gifmemore_update_path do |f| %>
                <%= f.input :id, as: :hidden %>
                <%= f.submit value: "set as default", class: 'btn btn-primary' %>
                <% end %>
                <% end %>

                <%= simple_form_for giphy, url: gifmemore_destroy_path, method: :delete do |f| %>
                <%= f.input :id, as: :hidden %>
                <%= f.submit value: "remove", class: 'btn btn-danger' %>
                <% end %>
              </div>
            </li>
            <li>
              by <span><%= giphy.creator.downcase %></span>
            </li>
            <li>
              default: <%= giphy.default ? raw("<i class='fa fa-check'></i>") : raw("<i class='fa fa-times'></i>") %>
            </li>
            <li>
              message:
              <div class="message-box">
                <%= giphy.message %>
              </div>
            </li>
          </ul>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/giphies/show.html.erb
<%= render partial: "shared/edit_button", locals: { partial_path: @giphy_path } %>

<h2 class="text-center marged">
  We love giphies, <span>send us one</span>
</h2>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-lg-6">
      <div class="giphy-image-container giphy-image-container-large" style="background-image:url('<%= @giphy_default.url %>');"></div>
      <div class="giphy-search-container">
        <form action="/" id="giphy-select-form" class="form-inline">
          <div class="form-group">
            <input type="text" id="keyword" name="keyword" class="form-control" placeholder="Enter a keyword">
            <input type="submit" class="btn btn-primary" value="Find me a giphy">
          </div>
        </form>
        <div class="hidden" id="giphy-url-placeholder"></div>
        <div class="giphy-featured">
          found by: <span><%= @giphy_default.creator %></span>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-lg-6">
      <div class="giphy-form-container">
        <%= simple_form_for @giphy, url: gifmemore_path do |f| %>
        <%= f.input :creator, placeholder: "Your name" %>
        <%= f.input :message, placeholder: "Leave us a message (It won't show on the wall)" %>
        <%= f.input :url, as: :hidden %>
        <%= f.submit class: "btn btn-primary", id: "giphy-submit-button", value:"Send your giphy" %>
        <% end %>
      </div>
    </div>
  </div>
  <h2 class="text-center marged">
    All our lovely giphies
  </h2>
  <div class="row">
    <% @giphies.each do |giphy| %>
    <div class="col-xs-6 col-lg-3">
      <div class="giphy-image-container giphy-image-container-small" style="background-image:url('<%= giphy.url %>');"></div>
      <div class="giphy-image-description">
        <p>
          by <span><%= giphy.creator.downcase %></span>
        </p>
      </div>
    </div>
    <% end %>
  </div>
</div>



<% content_for :after_js do %>
<%= javascript_include_tag 'giphy.js' %>
<% end %>

app/views/homes/edit.html.erb
<div class="devise-form-wrapper">
  <div class="devise-form">
    <%= simple_form_for @home, url: home_update_path do |f| %>
    <%= f.input :header %>
    <%= f.input :content %>
    <%= f.submit class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/homes/show.html.erb
<%= render partial: "shared/edit_button", locals: { partial_path: @home_path } %>
<%= render partial: "shared/banner", locals: 
{ 
  banner_image: "banner.png", 
  banner_home: true 
} %>
<%= render partial: "shared/content", locals: 
{ 
  content_hash: 
  {
    content: @home.content, 
    header: @home.header
  } 
} %>
<%= render partial: "shared/banner", locals: 
{ 
  banner_image: "animation.gif", 
  banner_home: false 
} %>

<% content_for :after_js do %>
    <%= javascript_include_tag 'banner.js' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TODO</title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <%= stylesheet_link_tag    'application', media: 'all' %>
</head>
<body>
  <%= render 'shared/navbar' %>
  <%= render 'shared/flashes' %>
  <%= yield %>
  <%= javascript_include_tag 'application' %>
  <%= yield :after_js %>
  <%= render 'shared/footer' %>
</body>
</html>

app/views/pages/blog.html.erb
<div class="blogposts">
  <h2>
    Blog
  </h2>
  <% if @post_collection.length == 1 %>
    <%= raw(@post_collection["description"]) %>
  <% else %>
    <% @posts.each do |post| %>
    <%= raw(post["description"]) %>
    <% end %>
  <% end %>
</div>

app/views/pages/contact.html.erb
<h2 class="text-center marged-small">
  contact information
</h2>
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-lg-6">
      <div class="text-right">
        <h3>
          B.Amsterdam
        </h3>
        <ul class="list-unstyled">
          <li>
            Johan Huizingalaan 763A
          </li>
          <li>
            1066 VH Amsterdam
          </li>
          <li>
            Netherlands
          </li>
        </ul>
        <ul class="list-unstyled">
          <li>
            +31 6 578 417 83
          </li>
          <li>
          <a href="MAILTO:love@weunfold.it?subject=Hello World">
              love@weunfold.it
            </a>
          </li>
        </ul>
      </div>
    </div>
    <div class="col-xs-12 col-lg-6">
      <div id="map"></div>
    </div>
  </div>
</div>


<%= render partial: "shared/maps" %>

app/views/pages/gifmemore.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-lg-6">
      <div class="giphy-image-container" style="background-image:url('https://media.giphy.com/media/26vUw5sYGcqmMDoBy/giphy.gif');"></div>
      <form action="/" id="giphy-form" class="form-inline">
        <div class="form-group">
          <input type="text" id="keyword" name="keyword" class="form-control">
          <input type="submit" class="btn btn-primary" value="Find me a giphy">
        </div>
      </form>
    </div>
    <div class="col-xs-12 col-lg-6">

    </div>
  </div>
</div>



<% content_for :after_js do %>
<%= javascript_include_tag 'giphy.js' %>
<% end %>

app/views/pages/home.html.erb
<%= render partial: "shared/banner", locals: { banner_image: "banner.png", banner_home: true } %>
<%= render partial: "shared/content", locals: { content_hash: @home_text } %>
<%= render partial: "shared/banner", locals: { banner_image: "animation.gif", banner_home: false } %>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image:url('<%= image_path banner_image %>');">
  <% if banner_home %>
  <div class="banner-content">
    <h3>
      unfold your
    </h3>
    <div class="changing-text-container">
      <h3 id="unfold-target"></h3>
    </div>
  </div>
  <% end %>
</div>

app/views/shared/_content.html.erb
<div class="content-box">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-lg-6">
        <div class="header-container">
          <div class="header">
            <h3>
              <%= content_hash[:header] %>
            </h3>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-lg-6">
        <div class="content-container">
          <div class="content">
            <p>
              <%= content_hash[:content] %>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_edit_button.html.erb
<% if user_signed_in? %>
  <%= link_to partial_path, class:"edit-button-round" do %>
    <i class="fa fa-pencil"></i>
  <% end %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <ul class="list-inline">
    <li>
      <i class="fa fa-facebook"></i>
    </li>
    <li>
      <i class="fa fa-twitter"></i>
    </li>
    <li>
      <i class="fa fa-pinterest"></i>
    </li>
    <li>
      <i class="fa fa-linkedin"></i>
    </li>
    <li>
      <i class="fa fa-envelope"></i>
    </li>
  </ul>
  <p>
    info@weunfold.it
  </p>
</div>

app/views/shared/_maps.html.erb
<!-- JAVASCRIPT REQUIREMENTS FOR GMAPS4RAILS -->

<% content_for :after_js do %>
  <%= javascript_include_tag "https://maps.google.com/maps/api/js?key=#{@api_key}" %>
  <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js' %>
  <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js' %>
  <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/js-marker-clusterer/1.0.0/markerclusterer_compiled.js' %>
  <%= javascript_include_tag 'https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' %>
  <%= javascript_include_tag 'https://cdn.rawgit.com/apneadiving/Google-Maps-for-Rails/master/js_compilation/gmaps_google.js' %>

  <%= javascript_include_tag 'map.js' %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-unfold">

  <div class="links">

    <ul class="list-inline hidden-xs">
      <li>
        <%= link_to "why", why_path, class: "link" %>
        <div class="underline"></div>
      </li>
      <li>
        <%= link_to "what", what_path, class: "link" %>
        <div class="underline"></div>
      </li>
      <li>
        <%= link_to "how", how_path, class: "link" %>
        <div class="underline"></div>
      </li>
      <li>
        <%= link_to "about", about_path, class: "link" %>
        <div class="underline"></div>
      </li>
    </ul>
    <%= link_to root_path do %>
    <%= image_tag "logo.png", class: "logo" %>
    <% end %>
    <ul class="list-inline hidden-xs">
      <li>
        <%= link_to "contact", contact_path, class: "link" %>
        <div class="underline"></div>
      </li>
      <li>
        <%= link_to "blog", blog_path, class: "link" %>
        <div class="underline"></div>
      </li>
      <li>
        <%= link_to "gif me more", gifmemore_path, class: "link" %>
        <div class="underline"></div>
      </li>
    </ul>
  </div>
  <div class="button-circle visible-xs">
    <button id="trigger-overlay" type="button">
      <i class="fa fa-bars"></i>
    </button>
  </div>
</div>


<div class="overlay overlay-contentscale">
  <button type="button" class="overlay-close">Close</button>
  <nav>
    <div class="overlay-container">
      <%= link_to "why", why_path, class: "link" %>

      <%= link_to "what", what_path, class: "link" %>

      <%= link_to "how", how_path, class: "link" %>

      <%= link_to "about", about_path, class: "link" %>

      <%= link_to "contact", contact_path, class: "link" %>

      <%= link_to "blog", blog_path, class: "link" %>

      <%= link_to "gif me more", gifmemore_path, class: "link" %>
    </div>
  </nav>
</div>

app/views/thoughts/edit.html.erb
<div class="devise-form-wrapper">
  <div class="devise-form">
  <%= simple_form_for @thought, url: why_update_path do |f| %>
    <%= f.input :header %>
    <%= f.input :description %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.submit class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/thoughts/show.html.erb
<%= render partial: "shared/edit_button", locals: { partial_path: @thought_path } %>

<div class="container">
  <h2 class="text-center marged-small">
    <%= @thought.header %>
  </h2>
  <div class="row">
    <div class="col-xs-12 col-lg-5 col-lg-offset-1">
      <div class="giphy-image-container giphy-image-container-medium" style="background-image:url('<%= @thought.photo %>')"></div>
    </div>
    <div class="col-xs-12 col-lg-5">
      <div class="content-box-simple">
        <p>
          <%= @thought.description %>
        </p>
      </div>
    </div>
  </div>
</div>